name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r analyzer/requirements.txt

    - name: Install spaCy model
      run: |
        python -m spacy download en_core_web_sm

    - name: Train the model
      run: |
        python analyzer/train_model.py

    - name: Install Bandit
      run: |
        python -m pip install bandit

    - name: Run Bandit Security Scan
      run: |
        bandit -r analyzer/ --severity-level high --exit-zero

    - name: Run tests
      run: |
        pytest --maxfail=5 --disable-warnings
